### ISSUE TITLE
Make server code modular by separating parts of 'express.js'

### ISSUE THREAD

**Issue by Frixoe** [MarleyPlant/Plugit#6]
Presently all of the server related code is in one file which makes it really hard to understand, scale and improve.

Suggest separating the following into modules somehow linking to the server and themselves(if necessary).

- Create a 'controllers' folder which will handle server requests made by the user regarding a certain. ex: dashboard requests could be written in 'dashboard.js' under 'controllers' folder.
- Create a 'passport' folder which will contain all code related to passport.
- Create a 'database' folder which will contain all code related to the database generation/setup.

Hopefully, these practices can help make the UI easily scale-able.

**Comment by MarleyPlant** [comment]
this would be extremely useful could you perhaps make a new branch with an appropriate file and folder structure following the guide in the wiki [here](https://github.com/MarleyPlant/Plugit/wiki/New-Feature-Or-Bug-Fix)

**Comment by Frixoe** [comment]
I would love to, and I've tried to, but it's really hard to figure out what code links to what :C

I'll still give it another try.

**Comment by MarleyPlant** [comment]
I have moved relevant code to the 'passport' and 'pg' files and I have also cleaned up some other code.

I have left the routes as I feel it might be better you doing them due to the fact you have more experience using Handlebars and Express
